### ISSUE TITLE
Folding this into the upstream?

### ISSUE THREAD

**Issue by DavidGriffith** [blurpy/minipro#2]
I was previously unaware there were problems with getting `minipro` going on OpenSUSE, because I really don't use that distribution and nobody seems to have submitted any OpenSUSE specific files.  So, I'd like to fold in what's here into the upstream at https://gitlab.com/DavidGriffith/minipro/.  Would you be interested in adapting what you have here to that repo?   

Specifically, I'd like you to adapt and update your `minipro.spec` file and add your build instructions to https://gitlab.com/DavidGriffith/minipro/-/blob/master/README.md.  I can go ahead now and add your more generic instructions to `README.md`.

**Comment by blurpy** [comment]
Sure, that sounds good to me. It's been a while since I built `minipro`, so let me see if I can get things up to date and working.

**Comment by blurpy** [comment]
Sorry for the late response @DavidGriffith. Finally had some time to sit down and work on this.

Made a merge request here: https://gitlab.com/DavidGriffith/minipro/-/merge_requests/219

**Comment by blurpy** [comment]
Thanks for merging my merge request @DavidGriffith.

**Comment by blurpy** [comment]
Followup for me:

 - [x] Change build instructions to point to the official repository
